### ISSUE TITLE
Idées d'évolutions

### ISSUE THREAD

**Issue by vdomos** [fritz-smh/domogik-plugin-callerid#1]
Hello,

Pas testé cette version du plugin (ma VM n'a pas accés au tél), mais je m'étais inspiré de ta version Domogik 0.3 pour en faire une MQTT sur un rpi B.

Si cela t'intéresse, je te donne le modem utlisé sous Linux car j'ai eu du mal à trouver la commande Hayes pour activer le CID, cela pourrait servir à d'autres intéressés par le plugin.

Modem USB 56k **Trendnet TFM-561U** :

```
CID_COMMAND = "AT+VCID=1"
```

Un ajout fait qui me semble un plus, j'ai créé un fichier annuaire en JSON pour renvoyer le nom plutot que le n° reçu:
Je ne sais pas si il serai possible de renseigner ce fichier directement dans Domogik.

```
{
    "0102030405" : "nom1",
    "0102030407" : "nom2",
    "0102030407" : "nom3",
     "P" : "masqué",
    "0147692869" : "blacklisté",
    "0956763191" : "blacklisté",
    "numero" : "nom"
}
```

Concernant la ligne "P", c'est ce que je reçoit si le n° est masqué avec ce modem.

Les 2 lignes "blacklisté" c'est une fonctionnalité que je n'ai pas mis en place mais qui me tente,
c'est de faire prendre la ligne par le modem (ATA) et raccrocher dans la foulée pour les indésirables ou les n° masqué :)

**Comment by fritz-smh** [comment]
Salut,

L'idée est bonne. J'ai dans ma TODO quelque chose dans le même esprit :  
- pouvoir renseigner dans la conf du plugin l'url d'un annuaire (owncloud, seafile, cozycloud, ...). De manière périodique (toutes les heures ?) le plugin mettrait à jour une liste en mémoire qui contient les contacts.
- remplacer le numéro par le nom si connu

Je n'avais pas pensé au blacklistage. On pourrait avoir une commande du plugin qui permette de blacklister un numéro, comme ça on ajoutes un bouton pour ça dans le widget d'historique des appels et c'est super simple.

Le coup du json me semble trop technique pour Madame Michu à maintenir. Le lien avec un owncloud ou autre également. On pourrait proposer les 2 possibilités (en complémentaire) au final : 
1. utilisation d'une liste locale au plugin
2. utilisation d'un owncloud/cozycloud/....

Pour le point 1, pour le moment nous pourrions en faire un simple fichier csv éditable en raw depuis l'onglet advanced du plugin. A teme il faudrait intégrer ça dans la gestion des personnes dans domogik (un projet à moyen terme, pas avant 2/3 versions je pense)

Accessoirement, il faut aussi que je donne la possiblité de changer la commande CID (via la conf avec une liste de choix).

**Comment by tikismoke** [comment]
En plus de owncloud pourquoi pas du carddav.
Ça serait compatible avec plein de truc (genre davical et autre serveur dav).

**Comment by fritz-smh** [comment]
c'est l'idée, owncloud est un exemple :)

**Comment by fritz-smh** [comment]
Traité dans la version 1.0

Done in 1.0 release
